# Generated by Django 4.1.3 on 2022-11-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='category_id',
        ),
    ]
